---
title: Avaliação de Políticas Públicas
subtitle: Lista de Exercícios
author: Alberson da Silva Miranda^[Discente PPGEco/UFES.]
date: last-modified
date-format: long
lang: pt-BR
thanks: Código disponível em https://github.com/albersonmiranda/politicas_publicas.
toc: true
toc-title: SUMÁRIO
number-sections: true
sansfont: Times New Roman # Liberation Serif
mainfont: Times New Roman # Liberation Serif
monofontoptions:
  - Scale=0.8
highlight-style: zenburn
code-line-numbers: true
format:
  pdf:
    documentclass: scrreprt
    header-includes: 
      - \renewcommand\thesubsection{\alph{subsection}}
      - \usepackage{csquotes}
---

# Q1

O banco de dados PIAA_2017-2018.xlsx contém informações desidentificadas sobre notas dos alunos e frequência na monitoria da disciplina Matemática I no departamento de economia nos anos 2017 e 2018. A tabela a seguir lista as variáveis contidas no banco de dados.

| Variável | Descrição |
|----------|-----------|
| ID       | Identificação do aluno |
| Semestre | Semestre no qual a disciplina foi cursada |
| Nota     | Nota do aluno |
| Faltas   | Número de faltas na disciplina |
| Situação | Situação final do aluno na disciplina |
| Presença | Número de seções de monitoria que o aluno foi |
| Período  | Número de períodos matriculado |
| Sexo     | Masculino ou feminino |

## a

\begin{displayquote}
Usando o pacote “TableOne” do R, faça um teste de balanceamento da amostra de acordo com uma variável que indica se o aluno foi a mais do que 4 seções de monitoria (tratamento). Faça esse teste sobre as seguintes variáveis: Faltas, Sexo Masculino, variáveis dummies para os semestres e variável dummy para alunos do primeiro período. O que você conclui sobre o balanceamento dos alunos entre tratados e não tratados?
\end{displayquote}

Em relação às faltas, a amostra está desbalanceada. A média de faltas dos alunos que frequentaram mais de 4 seções de monitoria é de 3,82, enquanto a média dos que frequentaram menos de 4 seções é de 17,11 faltas. Formalmente, no teste de diferença de médias, com um p-valor menor que 0.001, podemos rejeitar a hipótese nula de que as médias são iguais (sendo a diferença apenas por uma questão de aleatoriedade amostral).

Em relação ao sexo, sob a hipótese nula de proporções iguais, com p-valor de 0.511, o teste indica que a amostra está balanceada. A proporção de homens (sexo = Masculino) é de 68,9% entre os que não frequentaram mais de 4 seções de monitoria e de 62,2% entre os que frequentaram.



```{r q1.a}
# pacotes
library(tableone)

# carregar dados
dados <- readxl::read_excel("lista/data/PIAA_2017-2018.xlsx") |>
  janitor::clean_names()

# feature engineering
dados <- within(dados, {
  tratamento <- ifelse(presenca > 4, 1, 0)
  semestre <- as.factor(semestre)
  periodo <- as.factor(periodo)
  sexo <- as.factor(sexo)
  primeiro_periodo <- as.factor(ifelse(periodo == 1, 1, 0))
})

# tabela
tableone <- CreateTableOne(
  vars = c("faltas", "sexo", "semestre", "primeiro_periodo"),
  strata = "tratamento",
  data = dados
)
print(tableone, nonnormal = "faltas")
```