FROM ghcr.io/rocker-org/devcontainer/r-ver:"4.4"

RUN install2.r --error --skipinstalled -n -1 \
  # pacotes R
  mlr3verse \
  fabletools \

  && rm -rf /tmp/downloaded_packages

# Pacotes Python (digitar nomes em requirements.txt)
COPY requirements.txt /tmp/pip-tmp/
RUN python3 -m pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt